/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menudefotos;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Marcos Canul
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        BTNAzul = new javax.swing.JMenu();
        BTNAzul1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        BTNAzul2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        BTNAzul3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        BTNSalir = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNAzul.setText("Azul");

        BTNAzul1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        BTNAzul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/1 azul.png"))); // NOI18N
        BTNAzul1.setText("Azul1");
        BTNAzul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAzul1ActionPerformed(evt);
            }
        });
        BTNAzul.add(BTNAzul1);
        BTNAzul.add(jSeparator1);

        BTNAzul2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        BTNAzul2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/dos azul.png"))); // NOI18N
        BTNAzul2.setText("Azul2");
        BTNAzul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAzul2ActionPerformed(evt);
            }
        });
        BTNAzul.add(BTNAzul2);
        BTNAzul.add(jSeparator2);

        BTNAzul3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        BTNAzul3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Tres azul.png"))); // NOI18N
        BTNAzul3.setText("Azul3");
        BTNAzul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAzul3ActionPerformed(evt);
            }
        });
        BTNAzul.add(BTNAzul3);

        jMenuBar1.add(BTNAzul);

        jMenu3.setText("Verde");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Numero 1 Verde.png"))); // NOI18N
        jMenuItem1.setText("Verde1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);
        jMenu3.add(jSeparator3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Numero 2 Verde.png"))); // NOI18N
        jMenuItem2.setText("Verde2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);
        jMenu3.add(jSeparator4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Numero 3 Verde.png"))); // NOI18N
        jMenuItem3.setText("Verde3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Gris");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/1 gris.jpg"))); // NOI18N
        jMenuItem4.setText("Gris1");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);
        jMenu4.add(jSeparator5);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/numero 2 gris.jpg"))); // NOI18N
        jMenuItem5.setText("Gris2");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);
        jMenu4.add(jSeparator6);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/3 gris.jpg"))); // NOI18N
        jMenuItem6.setText("Gris3");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        BTNSalir.setText("Salir");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/Salida.png"))); // NOI18N
        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        BTNSalir.add(jMenuItem7);

        jMenuBar1.add(BTNSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNAzul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAzul1ActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/fotos/Azul1.jpg"));
        Image imagen = icono.getImage();        
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(700,400,Image.SCALE_SMOOTH));
        
        jLabel1.setIcon(iconoEscalado);
    }//GEN-LAST:event_BTNAzul1ActionPerformed

    private void BTNAzul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAzul2ActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/fotos/Azul2.jpg"));
        Image imagen = icono.getImage();        
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(700,400,Image.SCALE_SMOOTH));
        
        jLabel1.setIcon(iconoEscalado);
    }//GEN-LAST:event_BTNAzul2ActionPerformed

    private void BTNAzul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAzul3ActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/fotos/Azul3.jpg"));
        Image imagen = icono.getImage();        
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(700,400,Image.SCALE_SMOOTH));
        
        jLabel1.setIcon(iconoEscalado);
    }//GEN-LAST:event_BTNAzul3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/fotos/Verde1.jpg"));
        Image imagen = icono.getImage();        
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(700,400,Image.SCALE_SMOOTH));
        
        jLabel1.setIcon(iconoEscalado);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/fotos/Verde2.jpg"));
        Image imagen = icono.getImage();        
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(700,400,Image.SCALE_SMOOTH));
        
        jLabel1.setIcon(iconoEscalado);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/fotos/Verde3.jpg"));
        Image imagen = icono.getImage();        
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(700,400,Image.SCALE_SMOOTH));
        
        jLabel1.setIcon(iconoEscalado);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/fotos/Gris3.jpg"));
        Image imagen = icono.getImage();        
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(700,400,Image.SCALE_SMOOTH));
        
        jLabel1.setIcon(iconoEscalado);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/fotos/Gris1.jpg"));
        Image imagen = icono.getImage();        
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(700,400,Image.SCALE_SMOOTH));
        
        jLabel1.setIcon(iconoEscalado);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource("/fotos/Gris2.jpg"));
        Image imagen = icono.getImage();        
        ImageIcon iconoEscalado = new ImageIcon (imagen.getScaledInstance(700,400,Image.SCALE_SMOOTH));
        
        jLabel1.setIcon(iconoEscalado);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BTNAzul;
    private javax.swing.JMenuItem BTNAzul1;
    private javax.swing.JMenuItem BTNAzul2;
    private javax.swing.JMenuItem BTNAzul3;
    private javax.swing.JMenu BTNSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
